# Generated by Django 3.2.9 on 2022-01-28 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('H', 'Healthcare'), ('I', 'Information Technology'), ('Re', 'Real Estate and Development'), ('R', 'Retail'), ('Edu', 'Education'), ('G', 'Government'), ('E', 'Engineering'), ('D', 'Design'), ('A', 'Art'), ('S', 'Science')], max_length=50)),
                ('details', models.TextField(max_length=2000)),
                ('years_experience', models.IntegerField()),
                ('jobtitle', models.ManyToManyField(to='main_app.jobTitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
