# Generated by Django 3.2.9 on 2022-01-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='jobtitle',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='jobtitle',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_title',
            field=models.ManyToManyField(to='main_app.JobTitle'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='industry',
            field=models.CharField(choices=[('H', 'Healthcare'), ('IT', 'Information Technology'), ('RE', 'Real Estate and Development'), ('R', 'Retail'), ('EDU', 'Education'), ('G', 'Government'), ('E', 'Engineering'), ('D', 'Design'), ('A', 'Art'), ('S', 'Science')], max_length=50),
        ),
    ]
