# Generated by Django 3.2.9 on 2022-01-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220128_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='industry',
            field=models.CharField(choices=[('H', 'Healthcare'), ('IT', 'Information Technology'), ('RE', 'Real Estate and Development'), ('R', 'Retail'), ('EDU', 'Education'), ('G', 'Government'), ('E', 'Engineering'), ('D', 'Design'), ('A', 'Art'), ('S', 'Science')], max_length=27),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.ManyToManyField(to='main_app.JobTitle'),
        ),
    ]
