# Generated by Django 3.2.9 on 2022-01-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220131_1754'),
        ('main_app', '0003_auto_20220131_1824'),
    ]

    operations = [
    ]
