# Generated by Django 3.2.9 on 2022-01-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_jobpost_job_title'),
        ('main_app', '0004_merge_0003_auto_20220131_1754_0003_auto_20220131_1824'),
    ]

    operations = [
    ]
